name: Build Drivechain Launcher Project

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            godot_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_linux.x86_64.zip
            platform: "Linux/X11"
            extension: "x86_64"
          - os: macos-latest
            godot_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_macos.universal.zip
            platform: "Mac OS X"
            extension: "dmg"
          - os: windows-latest
            godot_url: https://github.com/godotengine/godot/releases/download/4.2.1-stable/Godot_v4.2.1-stable_win64.exe.zip
            platform: "Windows Desktop"
            extension: "exe"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Download and Extract Godot
      run: |
        wget ${{ matrix.godot_url }}
        unzip *.zip

    - name: Export Project
      run: |
        if [ ${{ matrix.os }} != 'windows-latest' ]; then
          chmod +x ./Godot_v4.2.1-stable_${{ matrix.platform }}.64
        fi
        ./Godot_v4.2.1-stable_${{ matrix.platform }}.64 --export "${{ matrix.platform }}" drivechain.${{ matrix.extension }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: drivechain-${{ matrix.platform }}
        path: drivechain.${{ matrix.extension }}
